--login page
SELECT * FROM TRUCK
SELECT * FROM EMPLOYEE
DROP TABLE EMPLOYEE
CREATE TABLE EMPLOYEE(
EMP_ID VARCHAR2(50),
EMP_NAME VARCHAR2(50),
VENDOR_ID VARCHAR2(50),
PRIMARY KEY(EMP_ID,VENDOR_ID)
)

SELECT * FROM LOGIN


CREATE TABLE LOGIN(
USER_ID VARCHAR2(20) PRIMARY KEY,
PASSWORD VARCHAR2(20),
ACCOUNT_TYPE VARCHAR2(30),
SUPERVISOR_ID VARCHAR2(20)
);
--store details
CREATE TABLE STORE(
STORE_NO VARCHAR2(20) PRIMARY KEY,
PHONE_NO NUMBER(11),
ADDRESS VARCHAR2(100),
MANAGER FOREIGN KEY REFERENCES LOGIN(USER_ID)
)
--to find out which product is belonging to 
CREATE TABLE PO_PRODUCT(
PO_NO FOREIGN KEY REFERENCES PURCHASE_ORDER(PO_NO),
PRODUCT_ID FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID),
QUANTITY NUMBER(5,2),
PRIMARY KEY(PO_NO,PRODUCT_ID)
)

--Module 2

--vendor
SELECT * FROM VENDOR
CREATE TABLE VENDOR(
V_NO VARCHAR2(20),
V_NAME VARCHAR2(255),
PH_NO1 NUMBER(10),
PH_NO2 NUMBER(10),
ADDRESS VARCHAR2(255),
DIRECT_TO_STORE VARCHAR2(10),
STATUS VARCHAR2(20)
)
SELECT * FROM VENDOR_PRODUCT
--vendor-product
CREATE TABLE VENDOR_PRODUCT(
V_NO FOREIGN KEY REFERENCES VENDOR(V_NO),
PRODUCT_ID FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID),
VAT VARCHAR2(20),
SERVICE VARCHAR2(20)
)

--Module 3-----

--Delivery Settlement at Dc---

CREATE TABLE DELIVERY_DC
(
BILL_NO VARCHAR2(20) FOREIGN KEY REFERENCES VENDOR_BILL(BILL_NO),
RECEIVED_DELIVERY_DATE DATE,
DELIVERY_TIME TIME,
DELIVERY_DELAYED BOOLEAN,
ACCEPTED_BY VARCHAR2(20),
ITEMS_RECEIVED NUMBER(25),
PENALTY_CHARGED NUMBER(25),
NO_OF DAYS_DELAYED NUMBER(10)
)


---Delivery Settlement at Store----

CREATE TABLE DELIVERY_STORE
(
BILL_NO VARCHAR2(20) FOREIGN KEY REFERENCES VENDOR_BILL(BILL_NO),
STORE_NO VARCHAR2(20) FOREIGN KEY REFERENCES STORE(STORE_NO),
PO_NO VARCHAR2(20) FOREIGN KEY REFERENCES PURCHASE_ORDER(PO_NO),
DC_NO VARCHAR2(20) FOREIGN KEY REFERENCES DCSTORE(DC_NO),
RECEIVED_DELIVERY_DATE DATE,
DELIVERY_TIME TIME,
DELIVERY_FROM VARCHAR2(20),
DELIVERY_DELAYED BOOLEAN,
ACCEPTED_BY VARCHAR2(20),
ITEMS_RECEIVED NUMBER(25),
PENALTY_CHARGED NUMBER(25),
NO_OF DAYS_DELAYED NUMBER(10)
)

---Defect Management--

----sequence for defect report id format=DFR####--
--select 'DFR'||to_char(DEFECT_REPORT_ID.nextval,'FM0999')from dual; --

CREATE SEQUENCE DEFECT_REPORT_ID
START WITH 1
INCREMENT BY 1;


CREATE TABLE DEFECT
(
DEFECT_REPORT_ID VARCHAR2(15) PRIMARY KEY,
V_NO VARCHAR2(20) FOREIGN KEY REFERENCES VENDOR(V_NO),
DAMAGE_TYPE VARCHAR2(25),
EMPLOYEE_ID VARCHAR2(20),
APPROVED_BY VARCHAR2(20),
RETAILER_NAME VARCHAR2(20),
STATUS VARCHAR2(10),
TOTAL_AMOUNT NUMBER(25)
)

CREATE TABLE REL_PRO_DEFECT
(
DEFECT_REPORT_ID VARCHAR2(15) FOREIGN KEY REFERENCES DEFECT(DEFECT_REPORT_ID),
PRODUCT_ID VARCHAR2(20) FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID),
BILL_NO VARCHAR2(20) FOREIGN KEY REFERENCES VENDOR_BILL(BILL_NO),
DC_NO VARCHAR2(20) FOREIGN KEY REFERENCES DCSTORE(DC_NO),
)

--truck

CREATE TABLE TRUCK(
TRUCK_NO VARCHAR2(20) PRIMARY KEY,
YEAR DATE,
OWNER VARCHAR2(20) FOREIGN KEY REFERENCES LOGIN(USER_ID)
)
